name: Power BI Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Power BI CLI
        run: |
          #npm install -g powerbi-cli
          npm i -g @powerbi-cli/powerbi-cli
          


      - name: List installed npm packages
        run: npm list -g --depth 0

      - name: Deploy PBIX to Power BI
        env:
          POWER_BI_CLIENT_ID: ${{ secrets.POWER_BI_CLIENT_ID }}
          POWER_BI_CLIENT_SECRET: ${{ secrets.POWER_BI_CLIENT_SECRET }}
          POWER_BI_TENANT_ID: ${{ secrets.POWER_BI_TENANT_ID }}
          POWER_BI_WORKSPACE_ID: ${{ secrets.POWER_BI_WORKSPACE_ID }}
          PBIX_FILE_PATH: ./path/to/your/report.pbix  # Replace with the actual path to your PBIX file
          DATASET_NAME: YourDatasetName  # Replace with your dataset name
          REPORT_NAME: YourReportName    # Replace with your report name
        run: |
          # Authenticate with Power BI CLI using Service Principal credentials
          pbicli login --service-principal  $POWER_BI_CLIENT_ID --secret $POWER_BI_CLIENT_SECRET --tenant $POWER_BI_TENANT_ID

          # Publish or update the dataset and report
          pbicli import -w $POWER_BI_WORKSPACE_ID -f $PBIX_FILE_PATH -d $DATASET_NAME -r $REPORT_NAME --overwrite
