name: Power BI Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power BI CLI
        run: npm install -g powerbi-cli

      - name: Deploy Power BI Reports
        env:
          POWERBI_WORKSPACE_ID: ${{ secrets.POWERBI_WORKSPACE_ID }}
          POWERBI_DATASET_NAME: reports
          POWERBI_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          POWERBI_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          POWERBI_TENANT: ${{ secrets.POWERBI_TENANT }}
        run: |
          pbicli login -i $POWERBI_CLIENT_ID -s $POWERBI_CLIENT_SECRET -t $POWERBI_TENANT
          pbicli import -w $POWERBI_WORKSPACE_ID -f reports/report.pbix -d "$POWERBI_DATASET_NAME"
          pbicli logout
#njvklfenv
